export var CustomerList=[
    {
     CustomerName:'CustomerA',
     CustomerEmail:'CustomerA@gmail.com',
     CustomerContact:'9944056692',
     CustomerId:1,
     CustomerStatus:'Active',
     checked:true
   },
   {
    CustomerName:'CustomerB',
    CustomerEmail:'CustomerB@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:2,
    CustomerStatus:'InActive',
    checked:false
    
  },
  {
    CustomerName:'CustomerC',
    CustomerEmail:'CustomerC@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:3,
    CustomerStatus:'Active',
    checked:true
  },
  {
    CustomerName:'CustomerD',
    CustomerEmail:'CustomerD@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:4,
    CustomerStatus:'InActive',
    checked:false
  },
  {
    CustomerName:'CustomerE',
    CustomerEmail:'CustomerE@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:5,
    CustomerStatus:'InActive',
    checked:false
  },
  {
    CustomerName:'CustomerF',
    CustomerEmail:'CustomerF@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:6,
    CustomerStatus:'Active',
     checked:true
  },
  {
    CustomerName:'CustomerG',
    CustomerEmail:'CustomerG@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:7,
    CustomerStatus:'Active',
    checked:true
  },
  {
    CustomerName:'CustomerH',
    CustomerEmail:'CustomerH@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:8,
    CustomerStatus:'Active',
    checked:true
  },    {
    CustomerName:'CustomerI',
    CustomerEmail:'CustomerI@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:9,
    CustomerStatus:'InActive',
    checked:false
  },
  {
    CustomerName:'CustomerJ',
    CustomerEmail:'CustomerJ@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:10,
    CustomerStatus:'InActive',
    checked:false
  },
  {
    CustomerName:'CustomerK',
    CustomerEmail:'CustomerK@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:11,
    CustomerStatus:'InActive',
    checked:false
  },
  {
    CustomerName:'CustomerL',
    CustomerEmail:'CustomerL@gmail.com',
    CustomerContact:'9944056692',
    CustomerId:12,
    CustomerStatus:'Active',
    checked:true
  }

]
