export const PromoCode=[
{
    promoId:1,
    OfferName:'Addidas',
    OfferCode:'ADI500',
    Expiry:'05/07/2022',
    DiscountType:'Flat',
    Status:'Active',
    checked:true
},
{
    promoId:2,
    OfferName:'Rebook50',
    OfferCode:'REB505',
    Expiry:'10/07/2022',
    DiscountType:'Percent',
    Status:'InActive',
    checked:false
},
{
    promoId:3,
    OfferName:'Nike',
    OfferCode:'Nike020',
    Expiry:'15/07/2022',
    DiscountType:'Flat',
    Status:'Active',
    checked:true
},
{
    promoId:4,
    OfferName:'Addidas',
    OfferCode:'ADI500',
    Expiry:'05/07/2022',
    DiscountType:'Flat',
    Status:'Active',
    checked:true
},
{
    promoId:5,
    OfferName:'Rebook50',
    OfferCode:'REB505',
    Expiry:'10/07/2022',
    DiscountType:'Percent',
    Status:'InActive',
    checked:false
},
{
    promoId:6,
    OfferName:'Nike',
    OfferCode:'Nike020',
    Expiry:'15/07/2022',
    DiscountType:'Flat',
    Status:'Active',
    checked:true
},
{
    promoId:7,
    OfferName:'Addidas',
    OfferCode:'ADI500',
    Expiry:'05/07/2022',
    DiscountType:'Flat',
    Status:'Active',
    checked:true
},
{
    promoId:8,
    OfferName:'Nike',
    OfferCode:'Nike020',
    Expiry:'15/07/2022',
    DiscountType:'Flat',
    Status:'Active',
    checked:true
},
]