export var VendorList=[
    {
     VendorName:'VendorA',
     VendorId:1,
     VendorStatus:'Active',
     checked:true
   },
   {
    VendorName:'VendorB',
    VendorId:2,
    VendorStatus:'InActive',
    checked:false
    
  },
  {
    VendorName:'VendorC',
    VendorId:3,
    VendorStatus:'Active',
    checked:true
  },
  {
    VendorName:'VendorD',
    VendorId:4,
    VendorStatus:'InActive',
    checked:false
  },
  {
    VendorName:'VendorE',
    VendorId:5,
    VendorStatus:'InActive',
    checked:false
  },
  {
    VendorName:'VendorF',
    VendorId:6,
    VendorStatus:'Active',
     checked:true
  },
  {
    VendorName:'VendorG',
    VendorId:7,
    VendorStatus:'Active',
    checked:true
  },
  {
    VendorName:'VendorH',
    VendorId:8,
    VendorStatus:'Active',
    checked:true
  },    {
    VendorName:'VendorI',
    VendorId:9,
    VendorStatus:'InActive',
    checked:false
  },
  {
    VendorName:'VendorJ',
    VendorId:10,
    VendorStatus:'InActive',
    checked:false
  },
  {
    VendorName:'VendorK',
    VendorId:11,
    VendorStatus:'InActive',
    checked:false
  },
  {
    VendorName:'VendorL',
    VendorId:12,
    VendorStatus:'Active',
    checked:true
  }

]
